#!/usr/bin/env python
# File generated by reverse AIRIUM translator (version 0.2.1).
# Any change will be overridden on next run.
# flake8: noqa E501 (line too long)

from airium import Airium

def generate_head():
    a = Airium()
    with a.head():
        a.meta(charset='utf-8')
        a.meta(content='width=device-width, initial-scale=1.0', name='viewport')
        a.title(_t='Shane Scott')
        a.link(href='css/foundation.css', rel='stylesheet')
        a.script(src='js/vendor/modernizr.js')
        a.link(href='tenta.ico', rel='shortcut icon')
        return a

def generate_body():
    a = Airium()
    with a.body():
        a('<!-- Navigation Bar! -->')
        with a.nav(klass='top-bar', **{'data-topbar': ''}):
            with a.ul(klass='title-area'):
                with a.li(klass='name'):
                    with a.h1():
                        a.a(href='index.html', _t='Shane Scott')
                with a.li(klass='toggle-topbar menu-icon'):
                    with a.a(href='#'):
                        a.span(_t='Menu')
            with a.section(klass='top-bar-section'):
                a('<!-- Left Nav Section -->')
                with a.ul(klass='left'):
                    with a.li():
                        a.a(href='cv_shane_scott.pdf', _t='CV')
                with a.ul(klass='left'):
                    with a.li():
                        a.a(href='researchings.html', _t='Research')
                with a.ul(klass='left'):
                    with a.li():
                        a.a(href='teachings.html', _t='Teaching')
                with a.ul(klass='left'):
                    with a.li():
                        a.a(href='mathings.html', _t='Math!')
        a('<!-- End Navigation Bar! -->')
        return a

def generate_bottom():
    a = Airium()
    a.script(src='js/vendor/jquery.js')
    a.script(src='js/foundation.min.js')
    with a.script():
        a('$(document).foundation();')
    return a

a = Airium()
a('<!DOCTYPE html>')
a(generate_head())
a(generate_body())
a(generate_bottom())

print(str(a))

